[package]
name = "smstatus-process"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "process"
path = "src/main.rs"

[dependencies]
extension-protocol = { workspace = true }
fmt-common = { path = "../../packages/fmt-common" }
libc = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
